#!/usr/bin/env bash
set -e

function prepare_package {
  printf 'Compiling "%s"... ' "$(basename "$1")"
  yarn -s babel "$1/src" -d "$1/dist" --ignore '**/__tests__' --copy-files
  remove_test_files "$1"
}

# Babel 7 changed how `--ignore` behaves, causing `--copy-files` to rebel and
# include test files and break coverage.
function remove_test_files {
  find "$1/dist" -type d -name __tests__ | while read -r test_dir; do
    rm -rf "$test_dir"
  done
}

find packages -maxdepth 1 -type d | while read -r pkg; do
  if [[ ! -f "$pkg/.babelrc" ]] || [[ ! -f "$pkg/package.json" ]]; then
    continue
  fi

  prepare_package "$pkg"
done
