#!/usr/bin/env bash
set -e

function prepare_package {
  printf 'Compiling "%s"... ' "$(basename "$1")"
  local babel="$PWD/node_modules/.bin/babel"

  (
    cd "$1"
    "$babel" src -d dist --ignore '**/__tests__' --copy-files -x .js,.ts
    remove_test_files
  )
}

# Babel 7 changed how `--ignore` behaves, causing `--copy-files` to rebel and
# include test files and break coverage.
function remove_test_files {
  find dist -type d -name __tests__ | while read -r test_dir; do
    rm -rf "$test_dir"
  done
}

find packages -maxdepth 1 -type d | while read -r pkg; do
  if [[ ! -f "$pkg/.babelrc" ]] || [[ ! -f "$pkg/package.json" ]]; then
    continue
  fi

  prepare_package "$pkg"
done
